'use strict'

export default {
	PROJECT_NAME: 'Project',

	LEADER_BOARD_PAGE: 'leaderBoard',

	ACTIONS: {
		GET_CURRENT_TOURNAMENT: 'GET_CURRENT_TOURNAMENT',
		GET_REAL_TIME_DATA: 'GET_REAL_TIME_DATA'
	}
}
